export const options = {
  "Cấp tỉnh": [
      "- Sở Nội vụ",
      "- Sở Nông nghiệp và Phát triển nông thôn",
      "- Đoàn khối Cơ quan – Doanh nghiệp tỉnh",
      "- Sở Lao động, Thương Binh và Xã hội",
      "- Sở Khoa học và Công nghệ",
      "- Ủy ban Mặt trận Tổ quốc Việt Nam tỉnh",
      "- Sở Giao thông vận tải",
      "- Sở Kế hoạch và Đầu tư",
      "- Sở Tài Chính",
      "- Sở Tài Nguyên và Môi trường",
      "- Sở Y tế",
      "- Thanh tra tỉnh",
      "- Tỉnh đoàn",
      "- Sở Xây dựng",
      "- Đài Phát thanh và Truyền hình Bến Tre",
      "- Sở Thông tin và Truyền thông",
      "- Sở Văn hóa, Thể thao và Du lịch",
      "- Sở Giáo dục và Đào tạo",
      "- Hội Liên hiệp phụ nữ tỉnh",
      "- Hội nông dân tỉnh",
      "- Hiệp hội doanh nghiệp tỉnh",
      "- Công an tỉnh",
      "- Liên Đoàn lao động tỉnh",
      "- Bảo hiểm xã hội tỉnh",
      "- Bộ Chỉ huy quân sự tỉnh",
      "- Sở Công Thương",
  ],
  "Cấp huyện": {
      " Huyện Mỏ Cày Nam": [
          "- Huyện đoàn Mỏ Cày Nam",
          "- Hội phụ nữ huyện Mỏ Cày Nam",
          "- Công an huyện Mỏ Cày Nam",
          "- Tòa án nhân dân huyện Mỏ Cày Nam",
          "- Ủy ban Mặt trận Tổ quốc huyện Mỏ Cày Nam",
          "- Viện Kiểm sát nhân dân huyện Mỏ Cày Nam",
          "- Ủy ban nhân dân huyện Mỏ Cày Nam",
      ],
      " Huyện Mỏ Cày Bắc": [
          "- Công an huyện Mỏ Cày Bắc",
          "- Hội phụ nữ huyện Mỏ Cày Bắc",
          "- Huyện đoàn Mỏ Cày Bắc",
          "- Tòa án nhân dân huyện Mỏ Cày Bắc",
          "- Ủy ban Mặt trận Tổ quốc huyện Mỏ Cày Bắc",
          "- Ủy ban nhân dân huyện Mỏ Cày Bắc",
          "- Viện Kiểm sát nhân dân huyện Mỏ Cày Bắc",

      ],
      " Huyện Châu Thành": [
          "- Công an huyện Châu Thành",
          "- Hội phụ nữ huyện Châu Thành",
          "- Huyện đoàn Châu Thành",
          "- Tòa án nhân dân huyện Châu Thành",
          "- Ủy ban Mặt trận Tổ quốc huyện Châu Thành",
          "- Ủy ban nhân dân huyện Châu Thành",
          "- Viện Kiểm sát nhân dân huyện Châu Thành",
      ],
      " Huyện Chợ Lách": [
          "- Công an huyện Chợ Lách",
          "- Hội phụ nữ huyện Chợ Lách",
          "- Huyện đoàn Chợ Lách",
          "- Tòa án nhân dân huyện Chợ Lách",
          "- Ủy ban Mặt trận Tổ quốc huyện Chợ Lách",
          "- Ủy ban nhân dân huyện Chợ Lách",
          "- Viện Kiểm sát nhân dân huyện Chợ Lách",
      ],
      " Huyện Bình Đại": [
          "- Công an huyện Bình Đại",
          "- Hội phụ nữ huyện Bình Đại",
          "- Huyện đoàn Bình Đại",
          "- Tòa án nhân dân huyện Bình Đại",
          "- Ủy ban Mặt trận Tổ quốc huyện Bình Đại",
          "- Ủy ban nhân dân huyện Bình Đại",
          "- Viện Kiểm sát nhân dân huyện Bình Đại",
      ],
      " Huyện Giồng Trôm": [
          "- Công an huyện Giồng Trôm",
          "- Hội phụ nữ huyện Giồng Trôm",
          "- Huyện đoàn Giồng Trôm",
          "- Tòa án nhân dân huyện Giồng Trôm",
          "- Ủy ban Mặt trận Tổ quốc huyện Giồng Trôm",
          "- Ủy ban nhân dân huyện Giồng Trôm",
          "- Viện Kiểm sát nhân dân huyện Giồng Trôm",
      ],
      " Huyện Thạnh Phú": [
          "- Công an huyện Thạnh Phú",
          "- Hội phụ nữ huyện Thạnh Phú",
          "- Huyện đoàn Thạnh Phú",
          "- Tòa án nhân dân huyện Thạnh Phú",
          "- Ủy ban Mặt trận Tổ quốc huyện Thạnh Phú",
          "- Ủy ban nhân dân huyện Thạnh Phú",
          "- Viện Kiểm sát nhân dân huyện Thạnh Phú",
      ],
      " Thành phố Bến Tre": [
          "- Công an Thành phố Bến Tre",
          "- Hội phụ nữ Thành phố Bến Tre",
          "- Huyện đoàn Thành phố Bến Tre",
          "- Tòa án nhân dân Thành phố Bến Tre",
          "- Ủy ban Mặt trận Tổ quốc Thành phố Bến Tre",
          "- Ủy ban nhân dân Thành phố Bến Tre",
          "- Viện Kiểm sát nhân dân Thành phố Bến Tre",
      ],
      " Huyện Ba Tri": [
          "- Công an huyện Ba Tri",
          "- Hội phụ nữ huyện Ba Tri",
          "- Huyện đoàn Ba Tri",
          "- Tòa án nhân dân huyện Ba Tri",
          "- Ủy ban Mặt trận Tổ quốc huyện Ba Tri",
          "- Ủy ban nhân dân huyện Ba Tri",
          "- Viện Kiểm sát nhân dân huyện Ba Tri",
      ],
  },
  "Cấp xã": [
      "Xã An Bình Tây - Huyện Ba Tri",
      "Xã An Điền - Huyện Thạnh Phú",
      "Xã An Định - Huyện Mỏ Cày Nam",
      "Xã An Đức - Huyện Ba Tri",
      "Xã An Hiệp - Huyện Ba Tri",
      "Xã An Hiệp - Huyện Châu Thành",
      "Xã An Hóa - Huyện Châu Thành",
      "Xã An Hòa Tây - Huyện Ba Tri",
      "Xã An Khánh - Huyện Châu Thành",
      "Xã An Ngãi Tây - Huyện Ba Tri",
      "Xã An Ngãi Trung - Huyện Ba Tri",
      "Xã An Nhơn - Huyện Thạnh Phú",
      "Xã An Phú Trung - Huyện Ba Tri",
      "Xã An Phước - Huyện Châu Thành",
      "Xã An Quy - Huyện Thạnh Phú",
      "Xã An Thạnh - Huyện Mỏ Cày Nam",
      "Xã An Thạnh - Huyện Thạnh Phú",
      "Xã An Thới - Huyện Mỏ Cày Nam",
      "Xã An Thuận - Huyện Thạnh Phú",
      "Xã Bảo Thạnh - Huyện Ba Tri",
      "Xã Bảo Thuận - Huyện Ba Tri",
      "Xã Bình Hòa - Huyện Giồng Trôm",
      "Xã Bình Khánh - Huyện Mỏ Cày Nam",
      "Xã Bình Phú - Thành phố Bến Tre",
      "Xã Bình Thành - Huyện Giồng Trôm",
      "Xã Bình Thạnh - Huyện Thạnh Phú",
      "Xã Bình Thắng - Huyện Bình Đại",
      "Xã Bình Thới - Huyện Bình Đại",
      "Xã Cẩm Sơn - Huyện Mỏ Cày Nam",
      "Xã Châu Bình - Huyện Giồng Trôm",
      "Xã Châu Hòa - Huyện Giồng Trôm",
      "Xã Châu Hưng - Huyện Bình Đại",
      "Xã Đa Phước Hội - Huyện Mỏ Cày Nam",
      "Xã Đại Điền - Huyện Thạnh Phú",
      "Xã Đại Hòa Lộc - Huyện Bình Đại",
      "Xã Định Thủy - Huyện Mỏ Cày Nam",
      "Xã Định Trung - Huyện Bình Đại",
      "Xã Giao Long - Huyện Châu Thành",
      "Xã Giao Thạnh - Huyện Thạnh Phú",
      "Xã Hòa Lộc - Huyện Mỏ Cày Bắc",
      "Xã Hòa Lợi - Huyện Thạnh Phú",
      "Xã Hòa Nghĩa - Huyện Chợ Lách",
      "Xã Hưng Khánh Trung A - Huyện Mỏ Cày Bắc",
      "Xã Hưng Khánh Trung B - Huyện Chợ Lách",
      "Xã Hưng Lễ - Huyện Giồng Trôm",
      "Xã Hưng Nhượng - Huyện Giồng Trôm",
      "Xã Hưng Phong - Huyện Giồng Trôm",
      "Xã Hương Mỹ - Huyện Mỏ Cày Nam",
      "Xã Hữu Định - Huyện Châu Thành",
      "Xã Khánh Thạnh Tân - Huyện Mỏ Cày Bắc",
      "Xã Long Định - Huyện Bình Đại",
      "Xã Long Hòa - Huyện Bình Đại",
      "Xã Long Mỹ - Huyện Giồng Trôm",
      "Xã Long Thới - Huyện Chợ Lách",
      "Xã Lộc Thuận - Huyện Bình Đại",
      "Xã Lương Hòa - Huyện Giồng Trôm",
      "Xã Lương Phú - Huyện Giồng Trôm",
      "Xã Lương Quới- Huyện Giồng Trôm",
      "Xã Minh Đức - Huyện Mỏ Cày Nam",
      "Xã Mỹ An - Huyện Thạnh Phú",
      "Xã Mỹ Chánh - Huyện Ba Tri",
      "Xã Mỹ Hòa - Huyện Ba Tri",
      "Xã Mỹ Hưng - Huyện Thạnh Phú",
      "Xã Mỹ Nhơn - Huyện Ba Tri",
      "Xã Mỹ Thạnh - Huyện Ba Tri",
      "Xã Mỹ Thạnh - Huyện Giồng Trôm",
      "Xã Mỹ Thạnh An - Thành phố Bến Tre"
  ]
}
